---
# tasks file for package
    - name: Install the package "git"
      apt:
          name: "{{ item }}"
          state: present
          update_cache: yes
      with_items:    
           - git
           - wget
           - tree
